###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "role": "client"
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "role": "admin"
}
###
GET http://localhost:3001/api/users/644c02a0b748e41db4a9520a

###
DELETE http://localhost:3001/api/users/644acfdccd5fdddb86584c7c
//Eliminar productos
###
GET http://localhost:3001/api/users/role/644c02a0b748e41db4a9520a

###
GET http://localhost:3001/api/users/Isinaveira